### ISSUE TITLE
Add variable for current octopi user

### ISSUE THREAD

**Issue by lpdunwell** [fabianonline/OctoPrint-Telegram#177] opened 2019-05-23 08:55 UTC
can we have a variable for the messages to show which octoprint user is responsible for prints and aborts?

**Comment by MarcusWolschon** [comment] 2019-05-23 10:54
Could you change the title to be more meaningful? Thanks.

**Comment by rlogiacco** [comment] 2019-07-18 00:59
Duplicate of #169.
I don't think this is easily doable. Would you like to submit a pull request?

**Closed by rlogiacco** 2019-07-18 00:59 UTC
Labels: duplicate, feature, needs feedback
